# Generated by Django 3.2.16 on 2022-12-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='slug',
        ),
    ]
