# Generated by Django 3.2.16 on 2022-12-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20221214_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='released_by',
            field=models.CharField(max_length=50),
        ),
    ]
