# Generated by Django 3.2.16 on 2022-12-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
