# Generated by Django 3.2.16 on 2022-12-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221212_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='age',
            field=models.PositiveIntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appuser',
            name='country',
            field=models.CharField(default='Bulgaria', max_length=20),
            preserve_default=False,
        ),
    ]
