# Generated by Django 3.2.16 on 2022-12-13 22:07

import django.core.validators
from django.db import migrations, models
import music_app.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221213_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5), music_app.core.validators.validate_only_letters]),
        ),
    ]
